const PDFDocument = require('pdfkit');
const fs = require('fs');
const path = require('path');

const doc = new PDFDocument({ margin: 50, size: 'A4' });
const outputPath = path.join(__dirname, '..', 'Capital_Spend_AI_Technical_Report.pdf');
const stream = fs.createWriteStream(outputPath);

doc.pipe(stream);

// --- Header ---
doc.rect(0, 0, 600, 150).fill('#0f172a');
doc.fillColor('#3b82f6').fontSize(32).font('Helvetica-Bold').text('Capital Spend AI', 50, 50);
doc.fillColor('#94a3b8').fontSize(12).font('Helvetica').text('TECHNICAL ARCHITECTURE & PROJECT DOCUMENTATION', 50, 90);
doc.moveDown(5);

// --- Introduction ---
doc.fillColor('#0f172a').fontSize(18).font('Helvetica-Bold').text('Project Overview', 50, 180);
doc.fontSize(11).font('Helvetica').fillColor('#334155').text(
    'Capital Spend AI is a sophisticated financial management application that leverages Artificial Intelligence to provide real-time spending insights. It is built using the modern MERN stack with a focus on premium user experience and low-latency AI interactions.',
    { align: 'justify' }
);
doc.moveDown(2);

// --- Tech Stack Section ---
doc.fontSize(18).font('Helvetica-Bold').fillColor('#0f172a').text('The Tech Stack (MERN + AI)');
doc.moveDown(1);

const techItems = [
    { title: 'MongoDB (Database)', desc: 'Used for its flexible NoSQL schema. It allows us to store complex objects like AI chat history and varied expense categories without the limitations of a relational database.' },
    { title: 'Express.js (Backend)', desc: 'A minimalist web framework for Node.js. It handles our API routing, authentication middleware, and secure communication with the AI engine.' },
    { title: 'React.js (Frontend)', desc: 'Utilized for building a reactive, high-performance user interface. Vite was chosen as the build tool for its lightning-fast development cycle.' },
    { title: 'Node.js (Runtime)', desc: 'The backbone of our server-side logic, enabling a unified JavaScript codebase from front to back.' },
    { title: 'Groq AI (Llama 3.3)', desc: 'Chosen for its extreme low-latency performance. Unlike OpenAI, Groq provides near-instant responses, making the chatbot feel conversational.' }
];

techItems.forEach(item => {
    doc.fillColor('#3b82f6').fontSize(12).font('Helvetica-Bold').text(item.title);
    doc.fillColor('#475569').fontSize(10).font('Helvetica').text(item.desc);
    doc.moveDown(1);
});

// --- Why these choices? ---
doc.addPage();
doc.rect(0, 0, 600, 50).fill('#1e293b');
doc.fillColor('#ffffff').fontSize(16).font('Helvetica-Bold').text('Why This Architecture?', 50, 18);
doc.moveDown(2);

const comparisons = [
    { q: 'Why MERN instead of Python/Django?', a: 'Using JavaScript for both Frontend and Backend (Node.js) allows for faster development, code sharing, and a more seamless data flow via JSON.' },
    { q: 'Why NoSQL (MongoDB) instead of SQL?', a: 'Financial data often evolves. MongoDB allows us to add new fields (like AI metadata) to transactions without expensive database migrations.' },
    { q: 'Why Groq instead of ChatGPT?', a: 'In financial apps, speed is everything. Groq\'s Llama 3.3 implementation is up to 10x faster than traditional LLM APIs, providing instant feedback on spending.' }
];

comparisons.forEach(item => {
    doc.fillColor('#0f172a').fontSize(11).font('Helvetica-Bold').text(item.q);
    doc.fillColor('#475569').fontSize(10).font('Helvetica').text(item.a);
    doc.moveDown(1.5);
});

// --- Workflow ---
doc.fontSize(18).font('Helvetica-Bold').fillColor('#0f172a').text('How It Works (System Workflow)');
doc.moveDown(1);
doc.fontSize(10).font('Helvetica').fillColor('#475569').text(
    '1. User adds an expense -> Frontend sends an authenticated POST request.\n' +
    '2. Backend validates JWT -> Stores encrypted data in MongoDB.\n' +
    '3. User asks AI a question -> Backend fetches current spending context (Budget vs. Actual).\n' +
    '4. Context + Question sent to Groq -> AI analyzes math and returns insights.\n' +
    '5. Frontend receives JSON -> UI updates reactively using React State.'
);

// --- Footer ---
doc.fillColor('#94a3b8').fontSize(8).text(
    `Generated by Antigravity AI for Capital Spend Project | ${new Date().toLocaleDateString()}`,
    50, 780, { align: 'center', width: 500 }
);

doc.end();

stream.on('finish', () => {
    console.log('✅ PDF Generated Successfully!');
    process.exit(0); // Explicitly exit only after file is saved
});

stream.on('error', (err) => {
    console.error('❌ Error saving PDF:', err);
    process.exit(1);
});
